install_red_venv: &INSTALL_RED_VENV
  install_red_script: |-
    python3.9 -m venv ~/redenv

    source ~/redenv/bin/activate

    python -m pip install -U pip setuptools wheel
    python -m pip install -U git+https://github.com/Cog-Creators/Red-DiscordBot@V3/develop#egg=Red-DiscordBot[postgres]

macos_catalina_task:
  macos_instance:
    image: catalina-base
  # using `.bash_profile` over `.profile` in CI-only (see GH-3852)
  install_instructions_script: |-
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"

    brew install python@3.9
    echo 'export PATH="/usr/local/opt/python@3.9/bin:$PATH"' >> ~/.bash_profile
    source ~/.bash_profile
    brew install git
    brew install --cask adoptopenjdk/openjdk/adoptopenjdk11

  <<: *INSTALL_RED_VENV

ubuntu_2004_focal_task:
  compute_engine_instance:
    image_project: ubuntu-os-cloud
    image: family/ubuntu-2004-lts
  # using `.bash_profile` over `.profile` in CI-only (see GH-3852)
  install_instructions_script: |-
    apt update
    apt -y install software-properties-common
    add-apt-repository -y ppa:git-core/ppa

    apt -y install python3.9 python3.9-dev python3.9-venv python3-pip git openjdk-11-jre-headless build-essential nano

  <<: *INSTALL_RED_VENV
