on:
  check_suite:
    type: ['completed']

name: Email about Cirrus CI failures
jobs:
  check_build_status:
    name: Check for Cirrus CI build status
    if: >-
      github.event.check_suite.app.name == 'Cirrus CI'
      && github.event.check_suite.conclusion != 'success'
      && github.event.check_suite.conclusion != 'cancelled'
    runs-on: ubuntu-latest
    outputs:
      conclusion: >-
        ${{
          fromJson(
            steps.get_on_build_finish_check_run.outputs.data
          ).check_runs[0].conclusion
        }}
    steps:
      - uses: octokit/request-action@v2.x
        id: get_on_build_finish_check_run
        with:
          route: GET /repos/${{ github.repository }}/check-suites/${{ github.event.check_suite.id }}/check-runs?check_name=on_build_finish
          mediaType: '{"previews": ["antiope"]}'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  fail_workflow:
    name: After Cirrus CI Failure
    needs: check_build_status
    if: needs.check_build_status.outputs.conclusion != 'neutral'
    runs-on: ubuntu-latest
    steps:
      - uses: octokit/request-action@v2.x
        id: get_failed_check_run
        with:
          route: GET /repos/${{ github.repository }}/check-suites/${{ github.event.check_suite.id }}/check-runs?status=completed
          mediaType: '{"previews": ["antiope"]}'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: |
          echo "Cirrus CI ${{ github.event.check_suite.conclusion }} on ${{ github.event.check_suite.head_branch }} branch!"
          echo "SHA ${{ github.event.check_suite.head_sha }}"
          echo $MESSAGE
          echo "##[error]See $CHECK_RUN_URL for details" && false
        env:
          CHECK_RUN_URL: ${{ fromJson(steps.get_failed_check_run.outputs.data).check_runs[0].html_url }}
