name: Test install instructions

on:
  workflow_dispatch:
  push:
  schedule:
    - cron: '5 16 * * *'

jobs:
  install:
    strategy:
      fail-fast: false
      matrix:
        include:
          # Arch Linux
          - container: archlinux:latest
            # using `--noconfirm` in CI-only
            run: |-
              pacman --noconfirm -Syu python python-pip git jre11-openjdk-headless base-devel nano

          # CentOS
          - container: centos:7
            # End of Maintenance Updates - 2024-06-30
            # https://wiki.centos.org/About/Product
            #
            # using `.profile` over `.bashrc` in CI-only
            # skipping `source .profile` as it's ran by bash automatically in next step
            run: |-
              yum -y groupinstall development
              yum -y install gcc zlib-devel bzip2 bzip2-devel readline-devel sqlite sqlite-devel openssl-devel tk-devel libffi-devel xz-devel java-11-openjdk-headless nano git
              yum -y install centos-release-scl
              yum -y install devtoolset-8-gcc devtoolset-8-gcc-c++
              echo "source scl_source enable devtoolset-8" >> ~/.profile

              yum -y install https://repo.ius.io/ius-release-el7.rpm
              yum -y swap git git224
            use_pyenv: true
          - container: centos:8
            # End of Maintenance Updates - 2021-12-31
            # https://wiki.centos.org/About/Product
            #
            run: |-
              dnf -y update
              dnf -y group install development
              dnf -y install python39 python39-pip python39-devel java-11-openjdk-headless nano git
          - container: tgagor/centos-stream:stream8
            # End of Maintenance Updates - 2024-05-31
            # https://wiki.centos.org/About/Product
            #
            run: |-
              dnf -y update
              dnf -y group install development
              dnf -y install python39 python39-pip python39-devel java-11-openjdk-headless nano git
          # Oracle Linux
          - container: oraclelinux:8
            # End of Premier Support - 2029-07-31
            # https://www.oracle.com/us/support/library/elsp-lifetime-069338.pdf
            #
            run: |-
              dnf -y update
              dnf -y group install development
              dnf -y install python39 python39-pip python39-devel java-11-openjdk-headless nano git
          # Rocky Linux
          - container: rockylinux/rockylinux
            # End of Extended Update Support - 2029-05-31
            # https://rockylinux.org/download
            #
            run: |-
              dnf -y update
              dnf -y group install development
              dnf -y install python39 python39-pip python39-devel java-11-openjdk-headless nano git

          # Debian
          - container: debian:buster
            # EOL ~2022-08
            # https://wiki.debian.org/DebianReleases#Production_Releases
            #
            run: |-
              apt update
              apt -y install make build-essential libssl-dev zlib1g-dev libbz2-dev libreadline-dev libsqlite3-dev wget curl llvm libncurses5-dev xz-utils tk-dev libxml2-dev libxmlsec1-dev libffi-dev liblzma-dev libgdbm-dev uuid-dev python3-openssl git openjdk-11-jre-headless nano
              CXX=/usr/bin/g++
            use_pyenv: true
          - container: debian:bullseye
            # EOL ~2024-09 (?)
            # https://wiki.debian.org/DebianReleases#Production_Releases
            #
            run: |-
              apt update
              apt -y install python3 python3-dev python3-venv python3-pip git openjdk-11-jre-headless build-essential nano

          - container: fedora:33
            # End of Life - 2021-11-16
            # https://fedorapeople.org/groups/schedule/f-35/f-35-all-tasks.html
            #
            run: |-
              dnf -y install python39 git java-11-openjdk-headless @development-tools nano
          - container: fedora:34
            # End of Life - 2022-05-17
            # https://fedorapeople.org/groups/schedule/f-36/f-36-all-tasks.html
            #
            run: |-
              dnf -y install python39 git java-11-openjdk-headless @development-tools nano
          - container: fedora:35
            # End of Life - 2022-05-17
            # https://fedorapeople.org/groups/schedule/f-37/f-37-all-tasks.html
            #
            run: |-
              dnf -y install python39 git java-11-openjdk-headless @development-tools nano

          # openSUSE
          - container: opensuse/leap:15.2
            # End of Life (planned) - 2021-12-31
            # https://en.opensuse.org/Lifetime#openSUSE_Leap
            #
            run: |-
              source /etc/os-release
              zypper -n ar -f https://download.opensuse.org/repositories/home:/Rotkraut:/Opt-Python/openSUSE_Leap_${VERSION_ID}/ Opt-Python
              zypper -n --gpg-auto-import-keys ref

              zypper -n install opt-python39 opt-python39-setuptools git-core java-11-openjdk-headless nano
              zypper -n install -t pattern devel_basis

              echo 'export PATH="/opt/python/bin:$PATH"' | tee /etc/profile.d/opt-python.sh
              source /etc/profile.d/opt-python.sh

              /opt/python/bin/python3.9 -m ensurepip --altinstall
          - container: opensuse/leap:15.3
            # End of Life (planned) - 2022-11-30
            # https://en.opensuse.org/Lifetime#openSUSE_Leap
            #
            run: |-
              source /etc/os-release
              zypper -n ar -f https://download.opensuse.org/repositories/home:/Rotkraut:/Opt-Python/openSUSE_Leap_${VERSION_ID}/ Opt-Python
              zypper -n --gpg-auto-import-keys ref

              zypper -n install opt-python39 opt-python39-setuptools git-core java-11-openjdk-headless nano
              zypper -n install -t pattern devel_basis

              echo 'export PATH="/opt/python/bin:$PATH"' | tee /etc/profile.d/opt-python.sh
              source /etc/profile.d/opt-python.sh

              /opt/python/bin/python3.9 -m ensurepip --altinstall
          - container: opensuse/tumbleweed:latest
            run: |-
              zypper -n install python39-base python39-pip git-core java-11-openjdk-headless nano
              zypper -n install -t pattern devel_basis

          - container: ubuntu:18.04
            # End of Standard Support - 2023-04-26
            # https://wiki.ubuntu.com/Releases#Current
            #
            run: |-
              apt update
              apt -y install software-properties-common
              add-apt-repository -y ppa:git-core/ppa

              add-apt-repository -y ppa:deadsnakes/ppa

              apt -y install python3.9 python3.9-dev python3.9-venv python3-pip git openjdk-11-jre-headless build-essential nano
          - container: ubuntu:20.04
            # End of Standard Support - 2025-04-23
            # https://wiki.ubuntu.com/Releases#Current
            #
            run: |-
              apt update
              apt -y install software-properties-common
              add-apt-repository -y ppa:git-core/ppa

              apt -y install python3.9 python3.9-dev python3.9-venv python3-pip git openjdk-11-jre-headless build-essential nano
          - container: ubuntu:rolling
            # Latest non-LTS Ubuntu
            #
            run: |-
              apt update
              apt -y install software-properties-common
              add-apt-repository -yu ppa:git-core/ppa

              apt -y install make build-essential libssl-dev zlib1g-dev libbz2-dev libreadline-dev libsqlite3-dev wget curl llvm libncurses5-dev xz-utils tk-dev libxml2-dev libxmlsec1-dev libffi-dev liblzma-dev libgdbm-dev uuid-dev python3-openssl git openjdk-11-jre-headless nano
              CXX=/usr/bin/g++
            use_pyenv: true

          # Windows
          - os: windows-latest
            run: |-
              Set-ExecutionPolicy Bypass -Scope Process -Force
              iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))
              choco upgrade git --params "/GitOnlyOnPath /WindowsTerminal" -y
              choco upgrade visualstudio2019-workload-vctools -y
              choco upgrade python3 -y --version 3.9.7

              choco upgrade adoptopenjdk11jre -y

          # macOS
          #
          # 1. using `.bash_profile` over `.profile` in CI-only (see GH-3852)
          #
          # 2. `brew upgrade` is required due to `brew install` failing
          # when package is already installed but outdated
          # This should probably be changed to something faster
          # but it is too much effort right now
          - os: macos-10.15
            run: |-
              /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"

              brew upgrade
              brew install python@3.9
              echo 'export PATH="/usr/local/opt/python@3.9/bin:$PATH"' >> ~/.bash_profile
              source ~/.bash_profile
              brew install git
              brew install --cask adoptopenjdk/openjdk/adoptopenjdk11
          - os: macos-11
            run: |-
              /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"

              brew upgrade
              brew install python@3.9
              echo 'export PATH="/usr/local/opt/python@3.9/bin:$PATH"' >> ~/.bash_profile
              source ~/.bash_profile
              brew install git
              brew install --cask adoptopenjdk/openjdk/adoptopenjdk11

    runs-on: ${{ matrix.os || 'ubuntu-latest' }}
    container: ${{ matrix.container }}
    env:
      DEBIAN_FRONTEND: noninteractive
    steps:
      # Installing requirements
      - name: Run install instructions (Linux/Mac)
        id: install_linux
        continue-on-error: ${{ matrix.container == 'opensuse/tumbleweed:latest' }}
        run: ${{ matrix.run }}
        if: >-
          runner.os != 'Windows'
        shell: bash -leo pipefail {0}

      - name: Run install instructions (Windows)
        run: ${{ matrix.run }}
        if: >-
          runner.os == 'Windows'
        shell: powershell

      - name: Install Python with pyenv
        if: >-
          steps.install_linux.outcome == 'success' && matrix.use_pyenv
        shell: bash -leo pipefail {0}
        # `echo` commands are CI-only - users have to add those lines on their own
        run: |-
          command -v pyenv && pyenv update || curl https://pyenv.run | bash

          echo 'export PATH="'$HOME'/.pyenv/bin:$PATH"' >> ~/.profile
          echo 'eval "$(pyenv init -)"' >> ~/.profile
          echo 'eval "$(pyenv init --path)"' >> ~/.profile
          echo 'eval "$(pyenv virtualenv-init -)"' >> ~/.profile
          source ~/.profile

          CONFIGURE_OPTS=--enable-optimizations pyenv install 3.9.7 -v

          pyenv global 3.9.7

      # Making a virtual environment and installing Red
      - name: Make a virtual environment (pyenv virtualenv)
        if: >-
          steps.install_linux.outcome == 'success' && matrix.use_pyenv
        shell: bash -leo pipefail {0}
        run: |-
          pyenv virtualenv redbot

          pyenv shell redbot

          python -m pip install -U pip setuptools wheel
          python -m pip install -U Red-DiscordBot[postgres]

      - name: Install Red inside venv (Linux/Mac)
        if: >-
          steps.install_linux.outcome == 'success' && !matrix.use_pyenv && runner.os != 'Windows'
        shell: bash -leo pipefail {0}
        run: |-
          python3.9 -m venv ~/redenv

          source ~/redenv/bin/activate

          python -m pip install -U pip setuptools wheel
          python -m pip install -U Red-DiscordBot[postgres]

      - name: Install Red inside venv (Windows)
        if: >-
          runner.os == 'Windows'
        shell: cmd
        run: |-
          py -3.9 -m venv "%userprofile%\redenv"

          "%userprofile%\redenv\Scripts\activate.bat"

          python -m pip install -U pip setuptools wheel
          python -m pip install -U Red-DiscordBot[postgres]

      - name: Ensure failure
        if: ${{ steps.install_linux.outcome == 'success' && matrix.container == 'opensuse/tumbleweed:latest' }}
        run: exit 1
