name: Test install instructions

on:
  workflow_dispatch:
  push:
  schedule:
    - cron: '5 16 * * *'

env:
  RED_PACKAGE_SPEC: |-
    ${{
      github.ref_name == 'dev' && 'Red-DiscordBot[postgres] @ https://github.com/Cog-Creators/Red-DiscordBot/tarball/V3/develop'
      || startsWith(github.ref_name, 'pull/') && format(
        'Red-DiscordBot[postgres] @ https://github.com/Cog-Creators/Red-DiscordBot/tarball/refs/{0}/merge',
        github.ref_name
      )
      || 'Red-DiscordBot[postgres]'
    }}
  PIP_ONLY_BINARY: ':all:'

jobs:
  install:
    strategy:
      fail-fast: false
      matrix:
        os:
          # x86_64
          - macos-12
          - macos-13
          # ARM
          - macos-14

    runs-on: ${{ matrix.os }}

    steps:
      # Clone Red-Install-Tests repository
      - uses: actions/checkout@v4

      # Before performing steps in GH Actions following steps are performed first:
      # 1. Remove python@3 and python@3.* executables
      # 2. Remove JAVA_HOME and symlinks used by /usr/libexec/java_home to find Java
      - name: Perform Actions runner system pre-cleanup
        run: |-
          rm -f /usr/local/bin/{2to3{,-3.*},{idle3,pydoc3}{,.*},python3{,.*}{,-config}}
          sed -i '' -E 's/^(export JAVA_HOME[^=]*=).*/\1/' ~/.bashrc
          sudo rm -f /Library/Java/JavaVirtualMachines/Temurin-Hotspot-*.jdk

      # Installing requirements on macOS
      - name: Run install instructions (Linux/Mac)
        run: |-
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          brew_location="$([ -n "$HOMEBREW_PREFIX" ] && echo "$HOMEBREW_PREFIX" || ([ "$(/usr/bin/uname -m)" = "arm64" ] && echo /opt/homebrew || echo /usr/local))/bin/brew"
          printf '\neval "$(%s shellenv)"\n' "$brew_location" >> "$([ -n "$ZSH_VERSION" ] && echo ~/.zprofile || ([ -f ~/.bash_profile ] && echo ~/.bash_profile || echo ~/.profile))"
          eval "$("$brew_location" shellenv)"

          brew install python@3.11
          brew install git
          brew install temurin@17

          echo 'export PATH="$(brew --prefix)/opt/python@3.11/bin:$PATH"' >> "$([ -n "$ZSH_VERSION" ] && echo ~/.zprofile || ([ -f ~/.bash_profile ] && echo ~/.bash_profile || echo ~/.profile))"
          export PATH="$(brew --prefix)/opt/python@3.11/bin:$PATH"
        shell: bash -leo pipefail {0}

      # Making a virtual environment and installing Red
      - name: Install Red inside venv on Python 3.11
        shell: bash -leo pipefail {0}
        run: |-
          python3.11 -m venv ~/redenv

          source ~/redenv/bin/activate

          python -m pip install -U pip setuptools wheel
          python -m pip install -U "$RED_PACKAGE_SPEC"

          ./check_java_version.py
      - name: Run tests inside venv on Python 3.11.
        shell: bash -leo pipefail {0}
        run: |-
          source ~/redenv/bin/activate
          python ./run_tests.py
