name: Test install instructions

on:
  workflow_dispatch:
  push:
  schedule:
    - cron: '5 16 * * *'

jobs:
  install:
    strategy:
      fail-fast: false
      matrix:
        include:
          # Arch Linux
          - container: archlinux:latest
            # using `--noconfirm` in CI-only
            run: |-
              pacman --noconfirm -Syu python python-pip git jre11-openjdk-headless base-devel nano
            venv_method: "venv310"

          # Alma Linux
          - container: almalinux:8
            # How long will CloudLinux support AlmaLinux? - 2029-05-31
            # https://wiki.almalinux.org/FAQ.html#how-long-will-cloudlinux-support-almalinux
            #
            run: |-
              dnf -y update
              dnf -y group install development
              dnf -y install python39 python39-pip python39-devel java-11-openjdk-headless nano git
              alternatives --set java "java-11-openjdk.$(uname -i)"
            venv_method: "venv39"
          # CentOS
          - container: centos:7
            # End of Maintenance Updates - 2024-06-30
            # https://wiki.centos.org/About/Product
            #
            # using `.profile` over `.bashrc` in CI-only
            # skipping `source .profile` as it's ran by bash automatically in next step
            run: |-
              yum -y groupinstall development
              yum -y install gcc zlib-devel bzip2 bzip2-devel readline-devel sqlite sqlite-devel openssl-devel tk-devel libffi-devel xz-devel java-11-openjdk-headless nano git
              yum -y install centos-release-scl
              yum -y install devtoolset-8-gcc devtoolset-8-gcc-c++
              echo "source scl_source enable devtoolset-8" >> ~/.profile

              yum -y install https://repo.ius.io/ius-release-el7.rpm
              yum -y swap git git236
            venv_method: "pyenv39"
          - container: quay.io/centos/centos:stream8
            # End of Maintenance Updates - 2024-05-31
            # https://wiki.centos.org/About/Product
            #
            run: |-
              dnf -y update
              dnf -y group install development
              dnf -y install python39 python39-pip python39-devel java-11-openjdk-headless nano git
              alternatives --set java "java-11-openjdk.$(uname -i)"
            venv_method: "venv39"
          - container: quay.io/centos/centos:stream9
            # Expected EOL - 2027-05-31
            # https://centos.org/stream9/#timeline
            #
            run: |-
              dnf -y install python39 git java-11-openjdk-headless @development nano
            venv_method: "venv39"
          # Oracle Linux
          - container: oraclelinux:8
            # End of Premier Support - 2029-07-31
            # https://www.oracle.com/us/support/library/elsp-lifetime-069338.pdf
            #
            run: |-
              dnf -y update
              dnf -y group install development
              dnf -y install python39 python39-pip python39-devel java-11-openjdk-headless nano git
              alternatives --set java "java-11-openjdk.$(uname -i)"
            venv_method: "venv39"
          # Rocky Linux
          - container: rockylinux/rockylinux
            # End of Extended Update Support - 2029-05-31
            # https://rockylinux.org/download
            #
            run: |-
              dnf -y update
              dnf -y group install development
              dnf -y install python39 python39-pip python39-devel java-11-openjdk-headless nano git
              alternatives --set java "java-11-openjdk.$(uname -i)"
            venv_method: "venv39"

          # Debian
          - container: debian:buster
            # EOL ~2022-08
            # https://wiki.debian.org/DebianReleases#Production_Releases
            #
            run: |-
              apt update
              apt -y install make build-essential libssl-dev zlib1g-dev libbz2-dev libreadline-dev libsqlite3-dev wget curl llvm libncursesw5-dev xz-utils tk-dev libxml2-dev libxmlsec1-dev libffi-dev liblzma-dev libgdbm-dev uuid-dev python3-openssl git openjdk-11-jre-headless nano
              CXX=/usr/bin/g++
            venv_method: "pyenv"
          - container: debian:bullseye
            # EOL ~2024-09 (?)
            # https://wiki.debian.org/DebianReleases#Production_Releases
            #
            run: |-
              apt update
              apt -y install python3 python3-dev python3-venv python3-pip git openjdk-11-jre-headless build-essential nano
            venv_method: "venv39"

          - container: fedora:34
            # End of Life - 2022-05-17
            # https://fedorapeople.org/groups/schedule/f-36/f-36-all-tasks.html
            #
            run: |-
              dnf -y install python3.10 git java-11-openjdk-headless @development-tools nano
            venv_method: "venv310"
          - container: fedora:35
            # End of Life - 2022-05-17
            # https://fedorapeople.org/groups/schedule/f-37/f-37-all-tasks.html
            #
            run: |-
              dnf -y install python3.10 git java-11-openjdk-headless @development-tools nano
            venv_method: "venv310"
          - container: fedora:36
            # End of Life - 2022-05-17
            # https://fedorapeople.org/groups/schedule/f-38/f-38-all-tasks.html
            #
            run: |-
              dnf -y install python3.10 git java-11-openjdk-headless @development-tools nano
            venv_method: "venv310"

          # openSUSE
          - container: opensuse/leap:15.3
            # End of Life (planned) - 2022-11-30
            # https://en.opensuse.org/Lifetime#openSUSE_Leap
            #
            run: |-
              zypper -n install python39-base python39-pip git-core java-11-openjdk-headless nano
              zypper -n install -t pattern devel_basis
            venv_method: "venv39"
          - container: opensuse/tumbleweed:latest
            run: |-
              zypper -n install python310-base python310-pip git-core java-11-openjdk-headless nano
              zypper -n install -t pattern devel_basis
            venv_method: "venv310"

          - container: ubuntu:18.04
            # End of Standard Support - 2023-04-26
            # https://wiki.ubuntu.com/Releases#Current
            #
            run: |-
              apt update
              apt -y install software-properties-common
              add-apt-repository -y ppa:git-core/ppa

              add-apt-repository -y ppa:deadsnakes/ppa

              apt -y install python3.10 python3.10-dev python3.10-venv python3-pip git openjdk-11-jre-headless build-essential nano
            venv_method: "venv310"
          - container: ubuntu:20.04
            # End of Standard Support - 2025-04-23
            # https://wiki.ubuntu.com/Releases#Current
            #
            run: |-
              apt update
              apt -y install python3.9 python3.9-dev python3.9-venv python3-pip git openjdk-11-jre-headless build-essential nano
            venv_method: "venv39"
          - container: ubuntu:22.04
            # End of Standard Support - 2027-04-21
            # https://wiki.ubuntu.com/Releases#Current
            #
            run: |-
              apt update
              apt -y install python3.10 python3.10-dev python3.10-venv python3-pip git openjdk-11-jre-headless build-essential nano
            venv_method: "venv310"
          - container: ubuntu:rolling
            # Latest non-LTS Ubuntu
            #
            run: |-
              apt update
              apt -y install python3.10 python3.10-dev python3.10-venv python3-pip git openjdk-11-jre-headless build-essential nano
            venv_method: "venv310"

          # Windows
          - os: windows-latest
            run: |-
              Set-ExecutionPolicy Bypass -Scope Process -Force
              iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))
              choco upgrade git --params "/GitOnlyOnPath /WindowsTerminal" -y
              choco upgrade visualstudio2022-workload-vctools -y
              choco upgrade python3 -y --version 3.10.4

              choco upgrade temurin11 -y
            venv_method: "windows"

          # macOS
          #
          # 1. using `.bash_profile` over `.profile` in CI-only (see GH-3852)
          #
          # 2. `brew upgrade` is required due to `brew install` failing
          # when package is already installed but outdated
          # This should probably be changed to something faster
          # but it is too much effort right now
          - os: macos-10.15
            run: |-
              /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"

              brew upgrade
              brew install python@3.10
              echo 'export PATH="/usr/local/opt/python@3.10/bin:$PATH"' >> ~/.bash_profile
              source ~/.bash_profile
              brew install git
              brew install --cask adoptopenjdk/openjdk/adoptopenjdk11
            venv_method: "venv310"
          - os: macos-11
            run: |-
              /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"

              brew upgrade
              brew install python@3.10
              echo 'export PATH="/usr/local/opt/python@3.10/bin:$PATH"' >> ~/.bash_profile
              source ~/.bash_profile
              brew install git
              brew install --cask adoptopenjdk/openjdk/adoptopenjdk11
            venv_method: "venv310"

    runs-on: ${{ matrix.os || 'ubuntu-latest' }}
    container: ${{ matrix.container }}
    env:
      DEBIAN_FRONTEND: noninteractive
      CHECK_JAVA_VERSION: |
        import re
        import subprocess
        import sys

        _RE_JAVA_VERSION_LINE_PRE223 = re.compile(
            r'version "1\.(?P<major>[0-8])\.(?P<minor>0)(?:_(?:\d+))?(?:-.*)?"'
        )
        _RE_JAVA_VERSION_LINE_223 = re.compile(
            r'version "(?P<major>\d+)(?:\.(?P<minor>\d+))?(?:\.\d+)*(\-[a-zA-Z0-9]+)?"'
        )

        process = subprocess.run(("java", "-version"), stderr=subprocess.PIPE, check=True)
        version_info = process.stderr.decode("utf-8")
        lines = version_info.splitlines()
        for line in lines:
            match = _RE_JAVA_VERSION_LINE_PRE223.search(line)
            if match is None:
                match = _RE_JAVA_VERSION_LINE_223.search(line)
            if match is None:
                continue
            major = int(match["major"])
            if major == 11:
                sys.exit(0)
            print(f"The detected Java version ({major}) is different from expected (11).")
            sys.exit(1)
        print("Couldn't determine Java version!")
        sys.exit(1)

    steps:
      # Installing requirements
      - name: Run install instructions (Linux/Mac)
        id: install_linux
        continue-on-error: ${{ matrix.container == 'opensuse/tumbleweed:latest' }}
        run: ${{ matrix.run }}
        if: >-
          runner.os != 'Windows'
        shell: bash -leo pipefail {0}

      - name: Run install instructions (Windows)
        run: ${{ matrix.run }}
        if: >-
          runner.os == 'Windows'
        shell: powershell

      - name: Install Python 3.9 with pyenv
        if: >-
          steps.install_linux.outcome == 'success' && matrix.venv_method == 'pyenv39'
        shell: bash -leo pipefail {0}
        # `echo` commands are CI-only - users have to add those lines on their own
        run: |-
          command -v pyenv && pyenv update || curl https://pyenv.run | bash

          echo 'export PATH="'$HOME'/.pyenv/bin:$PATH"' >> ~/.profile
          echo 'eval "$(pyenv init -)"' >> ~/.profile
          echo 'eval "$(pyenv init --path)"' >> ~/.profile
          echo 'eval "$(pyenv virtualenv-init -)"' >> ~/.profile
          source ~/.profile

          CONFIGURE_OPTS=--enable-optimizations pyenv install 3.9.13 -v

          pyenv global 3.9.13
          echo 'MY_PYTHON=python3.9' >> $GITHUB_ENV

      - name: Install Python 3.10 with pyenv
        if: >-
          steps.install_linux.outcome == 'success' && matrix.venv_method == 'pyenv'
        shell: bash -leo pipefail {0}
        # `echo` commands are CI-only - users have to add those lines on their own
        run: |-
          command -v pyenv && pyenv update || curl https://pyenv.run | bash

          echo 'export PATH="'$HOME'/.pyenv/bin:$PATH"' >> ~/.profile
          echo 'eval "$(pyenv init -)"' >> ~/.profile
          echo 'eval "$(pyenv init --path)"' >> ~/.profile
          echo 'eval "$(pyenv virtualenv-init -)"' >> ~/.profile
          source ~/.profile

          CONFIGURE_OPTS=--enable-optimizations pyenv install 3.10.4 -v

          pyenv global 3.10.4
          echo 'MY_PYTHON=python3.10' >> $GITHUB_ENV

      # Making a virtual environment and installing Red
      - name: Make a virtual environment (pyenv virtualenv)
        if: >-
          steps.install_linux.outcome == 'success' && (matrix.venv_method == 'pyenv' || matrix.venv_method == 'pyenv39')
        shell: bash -leo pipefail {0}
        run: |-
          pyenv virtualenv redbot

          pyenv shell redbot

          python -m pip install -U pip setuptools wheel
          python -m pip install -U git+https://github.com/jack1142/Red-DiscordBot@dep_changes#egg=Red-DiscordBot[postgres]

      - name: Install Red inside venv on Python 3.9 (Linux/Mac)
        if: >-
          steps.install_linux.outcome == 'success' && matrix.venv_method == 'venv39'
        shell: bash -leo pipefail {0}
        run: |-
          python3.9 -m venv ~/redenv

          source ~/redenv/bin/activate

          python -m pip install -U pip setuptools wheel
          python -m pip install -U git+https://github.com/jack1142/Red-DiscordBot@dep_changes#egg=Red-DiscordBot[postgres]
          echo 'MY_PYTHON=python3.9' >> $GITHUB_ENV

      - name: Install Red inside venv on Python 3.10 (Linux/Mac)
        if: >-
          steps.install_linux.outcome == 'success' && matrix.venv_method == 'venv310'
        shell: bash -leo pipefail {0}
        run: |-
          python3.10 -m venv ~/redenv

          source ~/redenv/bin/activate

          python -m pip install -U pip setuptools wheel
          python -m pip install -U git+https://github.com/jack1142/Red-DiscordBot@dep_changes#egg=Red-DiscordBot[postgres]
          echo 'MY_PYTHON=python3.10' >> $GITHUB_ENV

      - name: Install Red inside venv (Windows)
        if: >-
          runner.os == 'Windows'
        shell: cmd
        run: |-
          py -3.10 -m venv "%userprofile%\redenv"

          "%userprofile%\redenv\Scripts\activate.bat"

          python -m pip install -U pip setuptools wheel
          python -m pip install -U git+https://github.com/jack1142/Red-DiscordBot@dep_changes#egg=Red-DiscordBot[postgres]

      - name: Verify default Java version (Linux-only).
        if: >-
          steps.install_linux.outcome == 'success' && runner.os == 'Linux'
        shell: bash -leo pipefail {0}
        run: |-
          $MY_PYTHON -c "import os; exec(os.environ['CHECK_JAVA_VERSION'])"

      # - name: Ensure failure
      #   if: ${{ steps.install_linux.outcome == 'success' && matrix.container == 'opensuse/tumbleweed:latest' }}
      #   run: exit 1
